services:
  db:
    container_name: postgres_db
    restart: unless-stopped
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes: 
      - "./docker/init:/docker-entrypoint-initdb.d"
      - "./docker/data:/var/lib/postgresql/data"