services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
  db:
    container_name: postgres_db
    restart: unless-stopped
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes: 
      - "./docker/init:/docker-entrypoint-initdb.d"
      - "postgres_db_data:/var/lib/postgresql/data"

volumes:
  postgres_db_data:
    external: true