services:
  db:
    container_name: postgres_db
    restart: unless-stopped
    image: postgres:14
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes: 
      - "./docker/init:/docker-entrypoint-initdb.d:ro"
      - "postgres_db_data:/var/lib/postgresql/data"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
      - FLASK_DEBUG=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_db_data:
    external: true